server:
  port: 9092

spring:
  application:
    name: stock-server


  cloud:
    nacos:
      server-addr: http://localhost:8848
    alibaba:
      seata:
        tx-service-group: order_tx_group
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3341/stock
