server:
  port: 9090

spring:
  application:
    name: order-server


  cloud:
    nacos:
      server-addr: http://localhost:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3340/order?useUnicode=true&useSSL=false&characterEncoding=utf8
